#!/bin/bash

# Environment
RV=0
TMPDIR=$(mktemp -d)

# Run application
./bin/cpuusage -v -o out.html -f fopen,fwrite,fread,fclose ./ex001 &> ${TMPDIR}/out.txt

# Expected
# cpuusage: https://github.com/d99kris/cpuusage
# cpuusage: initializing
# cpuusage: starting program ./ex001
# cpuusage: processing output trace
# cpuusage: completed processing 36 samples

# Check result
LINE=$(cat ${TMPDIR}/out.txt | head -1 | tail -1)
EXPT="cpuusage: https://github.com/d99kris/cpuusage"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  echo "Full test output:"
  cat ${TMPDIR}/out.txt
  RV=1
fi

LINE=$(cat ${TMPDIR}/out.txt | head -2 | tail -1)
EXPT="cpuusage: initializing"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  echo "Full test output:"
  cat ${TMPDIR}/out.txt
  RV=1
fi

LINE=$(cat ${TMPDIR}/out.txt | head -3 | tail -1)
EXPT="cpuusage: starting program ./ex001"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  echo "Full test output:"
  cat ${TMPDIR}/out.txt
  RV=1
fi

LINE=$(cat ${TMPDIR}/out.txt | head -4 | tail -1)
EXPT="cpuusage: processing output trace"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  echo "Full test output:"
  cat ${TMPDIR}/out.txt
  RV=1
fi

LINE=$(cat ${TMPDIR}/out.txt | head -5 | tail -1)
EXPT="cpuusage: completed processing 36 samples"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  echo "Full test output:"
  cat ${TMPDIR}/out.txt
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}

