int    kill(pid_t a, int b);
int    killpg(pid_t a, int b);
void   psignal(int a, const char *b);
int    pthread_kill(pthread_t a, int b);
int    pthread_sigmask(int a, const sigset_t *restrict b, sigset_t *restrict c);
int    raise(int a);
int    sigaction(int a, const struct sigaction *restrict b, struct sigaction *restrict c);
//unsupported (undefined symbol sigbits): int    sigaddset(sigset_t *a, int b);
int    sigaltstack(const stack_t *restrict a, stack_t *restrict b);
//unsupported (undefined symbol sigbits): int    sigdelset(sigset_t *a, int b);
int    sigemptyset(sigset_t *a);
int    sigfillset(sigset_t *a);
int    sighold(int a);
int    sigignore(int a);
int    siginterrupt(int a, int b);
//unsupported (undefined symbol sigbits): int    sigismember(const sigset_t *a, int b);
sig_t  signal(int a, sig_t b);
int    sigpause(int a);
int    sigpending(sigset_t *a);
int    sigprocmask(int a, const sigset_t *restrict b, sigset_t *restrict c);
int    sigrelse(int a);
sig_t  sigset(int a, sig_t b);
int    sigsuspend(const sigset_t *a);
int    sigwait(const sigset_t *restrict a, int *restrict b);
