void     clearerr(FILE *a);
char    *ctermid(char *a);
int      dprintf(int a, const char *restrict b, ...)
int      fclose(FILE *a);
FILE    *fdopen(int a, const char *b);
int      feof(FILE *a);
int      ferror(FILE *a);
int      fflush(FILE *a);
int      fgetc(FILE *a);
int      fgetpos(FILE *restrict a, fpos_t *restrict b);
char    *fgets(char *restrict a, int b, FILE *restrict c);
int      fileno(FILE *a);
void     flockfile(FILE *a);
FILE    *fopen(const char *restrict a, const char *restrict b);
int      fprintf(FILE *restrict a, const char *restrict b, ...);
int      fputc(int a, FILE *b);
int      fputs(const char *restrict a, FILE *restrict b);
size_t   fread(void *restrict a, size_t b, size_t c, FILE *restrict d);
FILE    *freopen(const char *restrict a, const char *restrict b, FILE *restrict c);
int      fscanf(FILE *restrict a, const char *restrict b, ...);
int      fseek(FILE *a, long b, int c);
int      fseeko(FILE *a, off_t b, int c);
int      fsetpos(FILE *a, const fpos_t *b);
long     ftell(FILE *a);
off_t    ftello(FILE *a);
int      ftrylockfile(FILE *a);
void     funlockfile(FILE *a);
size_t   fwrite(const void *restrict a, size_t b, size_t c, FILE *restrict d);
int      getc(FILE *a);
int      getchar(void);
int      getc_unlocked(FILE *a);
int      getchar_unlocked(void);
ssize_t  getdelim(char **restrict a, size_t *restrict b, int c, FILE *restrict d);
ssize_t  getline(char **restrict a, size_t *restrict b, FILE *restrict c);
char    *gets(char *a);
int      pclose(FILE *a);
void     perror(const char *a);
FILE    *popen(const char *a, const char *b);
int      printf(const char *restrict a, ...);
int      putc(int a, FILE *b);
int      putchar(int a);
//unsupported (undefined symbol sputc): int      putc_unlocked(int a, FILE *b);
//unsupported (undefined symbol sputc): int      putchar_unlocked(int a);
int      puts(const char *a);
int      remove(const char *a);
int      rename(const char *a, const char *b);
int      renameat(int a, const char *b, int c, const char *d);
void     rewind(FILE *a);
int      scanf(const char *restrict a, ...);
void     setbuf(FILE *restrict a, char *restrict b);
int      setvbuf(FILE *restrict a, char *restrict b, int c, size_t d);
int      snprintf(char *restrict a, size_t b, const char *restrict c, ...);
int      sprintf(char *restrict a, const char *restrict b, ...);
int      sscanf(const char *restrict a, const char *restrict b, ...);
//unsupported (deprecated warning): char    *tempnam(const char *a, const char *b);
FILE    *tmpfile(void);
//unsupported (deprecated warning): char    *tmpnam(char *a);
int      ungetc(int a, FILE *b);
int      vdprintf(int a, const char *restrict b, va_list c);
int      vfprintf(FILE *restrict a, const char *restrict b, va_list c);
int      vfscanf(FILE *restrict a, const char *restrict b, va_list c);
int      vprintf(const char *restrict a, va_list b);
int      vscanf(const char *restrict a, va_list b);
int      vsnprintf(char *restrict a, size_t b, const char *restrict c, va_list d);
int      vsprintf(char *restrict a, const char *restrict b, va_list c);
int      vsscanf(const char *restrict a, const char *restrict b, va_list c);
