void    *memccpy(void *restrict a, const void *restrict b, int c, size_t d);
void    *memchr(const void *a, int b, size_t c);
int      memcmp(const void *a, const void *b, size_t c);
//unsupported (used by cpuusage): void    *memcpy(void *restrict a, const void *restrict b, size_t c);
//unsupported (used by cpuusage): void    *memmove(void *a, const void *b, size_t c);
//unsupported (used by cpuusage): void    *memset(void *a, int b, size_t c);
char    *stpcpy(char *restrict a, const char *restrict b);
char    *stpncpy(char *restrict a, const char *restrict b, size_t c);
char    *strcat(char *restrict a, const char *restrict b);
char    *strchr(const char *a, int b);
int      strcmp(const char *a, const char *b);
int      strcoll(const char *a, const char *b);
char    *strcpy(char *restrict a, const char *restrict b);
size_t   strcspn(const char *a, const char *b);
char    *strdup(const char *a);
char    *strerror(int a);
//unsupported (not common for platforms): int      strerror_r(int a, char *b, size_t c);
size_t   strlen(const char *a);
char    *strncat(char *restrict a, const char *restrict b, size_t c);
int      strncmp(const char *a, const char *b, size_t c);
char    *strncpy(char *restrict a, const char *restrict b, size_t c);
char    *strndup(const char *a, size_t b);
size_t   strnlen(const char *a, size_t b);
char    *strpbrk(const char *a, const char *b);
char    *strrchr(const char *a, int b);
char    *strsignal(int a);
size_t   strspn(const char *a, const char *b);
char    *strstr(const char *a, const char *b);
char    *strtok(char *restrict a, const char *restrict b);
char    *strtok_r(char *restrict a, const char *restrict b, char **restrict c);
size_t   strxfrm(char *restrict a, const char *restrict b, size_t c);
