double      acos(double a);
float       acosf(float a);
double      acosh(double a);
float       acoshf(float a);
long double acoshl(long double a);
long double acosl(long double a);
double      asin(double a);
float       asinf(float a);
double      asinh(double a);
float       asinhf(float a);
long double asinhl(long double a);
long double asinl(long double a);
double      atan(double a);
double      atan2(double a, double b);
float       atan2f(float a, float b);
long double atan2l(long double a, long double b);
float       atanf(float a);
double      atanh(double a);
float       atanhf(float a);
long double atanhl(long double a);
long double atanl(long double a);
double      cbrt(double a);
float       cbrtf(float a);
long double cbrtl(long double a);
double      ceil(double a);
float       ceilf(float a);
long double ceill(long double a);
double      copysign(double a, double b);
float       copysignf(float a, float b);
long double copysignl(long double a, long double b);
double      cos(double a);
float       cosf(float a);
double      cosh(double a);
float       coshf(float a);
long double coshl(long double a);
long double cosl(long double a);
double      erf(double a);
double      erfc(double a);
float       erfcf(float a);
long double erfcl(long double a);
float       erff(float a);
long double erfl(long double a);
double      exp(double a);
double      exp2(double a);
float       exp2f(float a);
long double exp2l(long double a);
float       expf(float a);
long double expl(long double a);
double      expm1(double a);
float       expm1f(float a);
long double expm1l(long double a);
double      fabs(double a);
float       fabsf(float a);
long double fabsl(long double a);
double      fdim(double a, double b);
float       fdimf(float a, float b);
long double fdiml(long double a, long double b);
double      floor(double a);
float       floorf(float a);
long double floorl(long double a);
double      fma(double a, double b, double c);
float       fmaf(float a, float b, float c);
long double fmal(long double a, long double b, long double c);
double      fmax(double a, double b);
float       fmaxf(float a, float b);
long double fmaxl(long double a, long double b);
double      fmin(double a, double b);
float       fminf(float a, float b);
long double fminl(long double a, long double b);
double      fmod(double a, double b);
float       fmodf(float a, float b);
long double fmodl(long double a, long double b);
double      frexp(double a, int * b);
float       frexpf(float a, int * b);
long double frexpl(long double a, int * b);
double      hypot(double a, double b);
float       hypotf(float a, float b);
long double hypotl(long double a, long double b);
int         ilogb(double a);
int         ilogbf(float a);
int         ilogbl(long double a);
double      j0(double a);
double      j1(double a);
double      jn(int a, double b);
double      ldexp(double a, int b);
float       ldexpf(float a, int b);
long double ldexpl(long double a, int b);
double      lgamma(double a);
float       lgammaf(float a);
long double lgammal(long double a);
long long   llrint(double a);
long long   llrintf(float a);
long long   llrintl(long double a);
long long   llround(double a);
long long   llroundf(float a);
long long   llroundl(long double a);
double      log(double a);
double      log10(double a);
float       log10f(float a);
long double log10l(long double a);
double      log1p(double a);
float       log1pf(float a);
long double log1pl(long double a);
double      log2(double a);
float       log2f(float a);
long double log2l(long double a);
double      logb(double a);
float       logbf(float a);
long double logbl(long double a);
float       logf(float a);
long double logl(long double a);
long        lrint(double a);
long        lrintf(float a);
long        lrintl(long double a);
long        lround(double a);
long        lroundf(float a);
long        lroundl(long double a);
double      modf(double a, double *b);
float       modff(float a, float *b);
long double modfl(long double a, long double *b);
double      nan(const char * a);
float       nanf(const char * a);
long double nanl(const char * a);
double      nearbyint(double a);
float       nearbyintf(float a);
long double nearbyintl(long double a);
double      nextafter(double a, double b);
float       nextafterf(float a, float b);
long double nextafterl(long double a, long double b);
double      nexttoward(double a, long double b);
float       nexttowardf(float a, long double b);
long double nexttowardl(long double a, long double b);
double      pow(double a, double b);
float       powf(float a, float b);
long double powl(long double a, long double b);
double      remainder(double a, double b);
float       remainderf(float a, float b);
long double remainderl(long double a, long double b);
double      remquo(double a, double b, int * c);
float       remquof(float a, float b, int *c);
long double remquol(long double a, long double b, int *c);
double      rint(double a);
float       rintf(float a);
long double rintl(long double a);
double      round(double a);
float       roundf(float a);
long double roundl(long double a);
double      scalbln(double a, long b);
float       scalblnf(float a, long b);
long double scalblnl(long double a, long b);
double      scalbn(double a, int b);
float       scalbnf(float a, int b);
long double scalbnl(long double a, int b);
double      sin(double a);
float       sinf(float a);
double      sinh(double a);
float       sinhf(float a);
long double sinhl(long double a);
long double sinl(long double a);
double      sqrt(double a);
float       sqrtf(float a);
long double sqrtl(long double a);
double      tan(double a);
float       tanf(float a);
double      tanh(double a);
float       tanhf(float a);
long double tanhl(long double a);
long double tanl(long double a);
double      tgamma(double a);
float       tgammaf(float a);
long double tgammal(long double a);
double      trunc(double a);
float       truncf(float a);
long double truncl(long double a);
double      y0(double a);
double      y1(double a);
double      yn(int a, double b);
