int       iswalnum_l(wint_t a, locale_t b);
int       iswalpha_l(wint_t a, locale_t b);
int       iswblank(wint_t a);
int       iswblank_l(wint_t a, locale_t b);
int       iswcntrl_l(wint_t a, locale_t b);
int       iswctype_l(wint_t a, wctype_t b, locale_t c);
int       iswdigit_l(wint_t a, locale_t b);
int       iswgraph_l(wint_t a, locale_t b);
int       iswlower_l(wint_t a, locale_t b);
int       iswprint_l(wint_t a, locale_t b);
int       iswpunct_l(wint_t a, locale_t b);
int       iswspace_l(wint_t a, locale_t b);
int       iswupper_l(wint_t a, locale_t b);
int       iswxdigit_l(wint_t a, locale_t b);
wint_t    towctrans(wint_t a, wctrans_t b);
wint_t    towctrans_l(wint_t a, wctrans_t b, locale_t c);
wint_t    towlower_l(wint_t a, locale_t b);
wint_t    towupper_l(wint_t a, locale_t b);
wctrans_t wctrans(const char *a);
wctrans_t wctrans_l(const char *a, locale_t b);
wctype_t  wctype_l(const char *a, locale_t b);
