double               cabs(double complex a);
float                cabsf(float complex a);
long double          cabsl(long double complex a);
double complex       cacos(double complex a);
float complex        cacosf(float complex a);
double complex       cacosh(double complex a);
float complex        cacoshf(float complex a);
long double complex  cacoshl(long double complex a);
long double complex  cacosl(long double complex a);
double               carg(double complex a);
float                cargf(float complex a);
long double          cargl(long double complex a);
double complex       casin(double complex a);
float complex        casinf(float complex a);
double complex       casinh(double complex a);
float complex        casinhf(float complex a);
long double complex  casinhl(long double complex a);
long double complex  casinl(long double complex a);
double complex       catan(double complex a);
float complex        catanf(float complex a);
double complex       catanh(double complex a);
float complex        catanhf(float complex a);
long double complex  catanhl(long double complex a);
long double complex  catanl(long double complex a);
double complex       ccos(double complex a);
float complex        ccosf(float complex a);
double complex       ccosh(double complex a);
float complex        ccoshf(float complex a);
long double complex  ccoshl(long double complex a);
long double complex  ccosl(long double complex a);
double complex       cexp(double complex a);
float complex        cexpf(float complex a);
long double complex  cexpl(long double complex a);
double               cimag(double complex a);
float                cimagf(float complex a);
long double          cimagl(long double complex a);
double complex       clog(double complex a);
float complex        clogf(float complex a);
long double complex  clogl(long double complex a);
double complex       conj(double complex a);
float complex        conjf(float complex a);
long double complex  conjl(long double complex a);
double complex       cpow(double complex a, double complex b);
float complex        cpowf(float complex a, float complex b);
long double complex  cpowl(long double complex a, long double complex b);
double complex       cproj(double complex a);
float complex        cprojf(float complex a);
long double complex  cprojl(long double complex a);
double               creal(double complex a);
float                crealf(float complex a);
long double          creall(long double complex a);
double complex       csin(double complex a);
float complex        csinf(float complex a);
double complex       csinh(double complex a);
float complex        csinhf(float complex a);
long double complex  csinhl(long double complex a);
long double complex  csinl(long double complex a);
double complex       csqrt(double complex a);
float complex        csqrtf(float complex a);
long double complex  csqrtl(long double complex a);
double complex       ctan(double complex a);
float complex        ctanf(float complex a);
double complex       ctanh(double complex a);
float complex        ctanhf(float complex a);
long double complex  ctanhl(long double complex a);
long double complex  ctanl(long double complex a);
