void              endhostent(void);
void              endnetent(void);
void              endprotoent(void);
void              endservent(void);
void              freeaddrinfo(struct addrinfo *a);
const char       *gai_strerror(int a);
int               getaddrinfo(const char *restrict a, const char *restrict b, const struct addrinfo *restrict c, struct addrinfo **restrict d);
struct hostent   *gethostent(void);
int               getnameinfo(const struct sockaddr *restrict a, socklen_t b, char *restrict c, socklen_t d, char *restrict e, socklen_t f, int g);
struct netent    *getnetbyaddr(uint32_t a, int b);
struct netent    *getnetbyname(const char *a);
struct netent    *getnetent(void);
struct protoent  *getprotobyname(const char *a);
struct protoent  *getprotobynumber(int a);
struct protoent  *getprotoent(void);
struct servent   *getservbyname(const char *a, const char *b);
struct servent   *getservbyport(int a, const char *b);
struct servent   *getservent(void);
void              sethostent(int a);
void              setnetent(int a);
void              setprotoent(int a);
void              setservent(int a);
