int   posix_spawn(pid_t *restrict a, const char *restrict b, const posix_spawn_file_actions_t *c, const posix_spawnattr_t *restrict d, char *const e[restrict], char *const f[restrict]);
int   posix_spawn_file_actions_addclose(posix_spawn_file_actions_t *a, int b);
int   posix_spawn_file_actions_adddup2(posix_spawn_file_actions_t *a, int b, int c);
int   posix_spawn_file_actions_addopen(posix_spawn_file_actions_t *restrict a, int b, const char *restrict c, int d, mode_t e);
int   posix_spawn_file_actions_destroy(posix_spawn_file_actions_t *a);
int   posix_spawn_file_actions_init(posix_spawn_file_actions_t *a);
int   posix_spawnattr_destroy(posix_spawnattr_t *a);
int   posix_spawnattr_getflags(const posix_spawnattr_t *restrict a, short *restrict b);
int   posix_spawnattr_getpgroup(const posix_spawnattr_t *restrict a, pid_t *restrict b);
int   posix_spawnattr_getschedparam(const posix_spawnattr_t *restrict a, struct sched_param *restrict b);
int   posix_spawnattr_getschedpolicy(const posix_spawnattr_t *restrict a, int *restrict b);
int   posix_spawnattr_getsigdefault(const posix_spawnattr_t *restrict a, sigset_t *restrict b);
int   posix_spawnattr_getsigmask(const posix_spawnattr_t *restrict a, sigset_t *restrict b);
int   posix_spawnattr_init(posix_spawnattr_t *a);
int   posix_spawnattr_setflags(posix_spawnattr_t *a, short b);
int   posix_spawnattr_setpgroup(posix_spawnattr_t *a, pid_t b);
int   posix_spawnattr_setschedparam(posix_spawnattr_t *restrict a, const struct sched_param *restrict b);
int   posix_spawnattr_setschedpolicy(posix_spawnattr_t *a, int b);
int   posix_spawnattr_setsigdefault(posix_spawnattr_t *restrict a, const sigset_t *restrict b);
int   posix_spawnattr_setsigmask(posix_spawnattr_t *restrict a, const sigset_t *restrict b);
int   posix_spawnp(pid_t *restrict a, const char *restrict b, const posix_spawn_file_actions_t *c, const posix_spawnattr_t *restrict d, char *const e[restrict], char *const f[restrict]);
